GET http://localhost:8080/hello
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdWRpZW5jZSI6InR3cnNwcnNlYyIsInN1YmplY3QiOiJUaG9tYXMiLCJpc3N1ZXIiOiJUaG9tYXMiLCJhdXRob3JpdGllcyI6IldSSVRFX0FSVElDTEV8REVMRVRFX0FSVElDTEV8UFJPQ0VTU19IRUxMT3xSRUFEX09SREVSfENSRUFURV9BUlRJQ0xFfERFTEVURV9PUkRFUnxXUklURV9PUkRFUnxSRUFEX0FSVElDTEV8Q1JFQVRFX09SREVSIiwiZXhwIjoxNjE2MzQyOTc2fQ.vT8mzW2-XQVXxTyX0_G_ogO4xpPXZh-bJtNKwrYPgF-KuhGmPaz853vaxP2N5wmI7ESdtafM1ibil-PTliWG3Q

<> 2021-03-21T151414.200.txt

###

GET http://localhost:8080/hello
Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdWRpZW5jZSI6InR3cnNwcnNlYyIsInN1YmplY3QiOiJUaG9tYXMiLCJpc3N1ZXIiOiJUaG9tYXMiLCJhdXRob3JpdGllcyI6IldSSVRFX0FSVElDTEV8REVMRVRFX0FSVElDTEV8UFJPQ0VTU19IRUxMT3xSRUFEX09SREVSfENSRUFURV9BUlRJQ0xFfERFTEVURV9PUkRFUnxXUklURV9PUkRFUnxSRUFEX0FSVElDTEV8Q1JFQVRFX09SREVSIiwiZXhwIjoxNjE2MzQyOTc2fQ.vT8mzW2-XQVXxTyX0_G_ogO4xpPXZh-bJtNKwrYPgF-KuhGmPaz853vaxP2N5wmI7ESdtafM1ibil-PTliWG3Q:

<> 2021-03-21T151347.400.html

###

POST http://localhost:8080/login?username=Thomas&password=Passw0rt

###

GET http://localhost:8080/articles/123
Authorization: Basic John Passw0rt

###

POST http://localhost:8080/login?username=Thomas&password=Passw0rt

###

POST http://localhost:8080/login?username=Thomas&password=Passw0rt

###

POST http://localhost:8080/articles
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdWRpZW5jZSI6InR3cnNwcnNlYyIsInN1YmplY3QiOiJUaG9tYXMiLCJpc3N1ZXIiOiJUaG9tYXMiLCJhdXRob3JpdGllcyI6IlJFQURfQVJUSUNMRXxXUklURV9BUlRJQ0xFfENSRUFURV9BUlRJQ0xFfFdSSVRFX09SREVSfERFTEVURV9PUkRFUnxERUxFVEVfQVJUSUNMRXxSRUFEX09SREVSfENSRUFURV9PUkRFUnxQUk9DRVNTX0hFTExPIiwiZXhwIjoxNjE2MTU3MTU5fQ.pfZ_yEb4vCpyYnngj-vhlhWt5DnE0ZBoBaJhcR0Qm_8Nc4Y6uDg5z-vYepwtTSkGY7R8yovGmayTveO2cwF_zQ

###

POST http://localhost:8080/login?username=Thomas&password=Passw0rt

###

GET http://localhost:8080/hello
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdWRpZW5jZSI6InR3cnNwcnNlYyIsInN1YmplY3QiOiJUaG9tYXMiLCJpc3N1ZXIiOiJUaG9tYXMiLCJhdXRob3JpdGllcyI6IldSSVRFX0FSVElDTEV8V1JJVEVfT1JERVJ8REVMRVRFX0FSVElDTEV8REVMRVRFX09SREVSfENSRUFURV9BUlRJQ0xFfFJFQURfT1JERVJ8Q1JFQVRFX09SREVSfFBST0NFU1NfSEVMTE98UkVBRF9BUlRJQ0xFIiwiZXhwIjoxNjE1NzE5ODE4fQ.nVjPlhCIg2cIWUU0Z8A-nhz9VeDoZNYL0mecAk3er065fklNI1pOt85f7Az8JfQgNlAjgLBG7kutJtwrnBvYaw

###

POST http://localhost:8080/articles
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdWRpZW5jZSI6InR3cnNwcnNlYyIsInN1YmplY3QiOiJUaG9tYXMiLCJpc3N1ZXIiOiJUaG9tYXMiLCJhdXRob3JpdGllcyI6IlBST0NFU1NfSEVMTE98REVMRVRFX0FSVElDTEV8Q1JFQVRFX09SREVSfFdSSVRFX0FSVElDTEV8UkVBRF9PUkRFUnxERUxFVEVfT1JERVJ8V1JJVEVfT1JERVJ8UkVBRF9BUlRJQ0xFfENSRUFURV9BUlRJQ0xFIiwiZXhwIjoxNjE1NzQxMzg2fQ.5ftYvnPF2Mzf6vfFGr67TxsDzWD_u4cU1_huo4WzZa8v9HM2_OHQ-pXeZC67AHVnN7_cVSe1c36ri2tqqiJcQQ

###

POST http://localhost:8080/articles

###

POST http://localhost:8080/articles
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdWRpZW5jZSI6InR3cnNwcnNlYyIsInN1YmplY3QiOiJKb2huIiwiaXNzdWVyIjoiVGhvbWFzIiwiYXV0aG9yaXRpZXMiOiJDUkVBVEVfT1JERVJ8UkVBRF9PUkRFUnxERUxFVEVfT1JERVJ8V1JJVEVfT1JERVJ8UkVBRF9BUlRJQ0xFIiwiZXhwIjoxNjE1NzQxNDI4fQ.OIoafTfKy-6Vi6FJ_tig1qVy-Iz-v23-x4IDk_hitH40JlZN5RxxlSqj2rtK-B1J12S3iEwh_irs0I04TomTcg

<> 2021-03-14T160359.403.json

###

POST http://localhost:8080/login?username=John&password=Passw0rt

###

POST http://localhost:8080/articles
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdWRpZW5jZSI6InR3cnNwcnNlYyIsInN1YmplY3QiOiJKb2huIiwiaXNzdWVyIjoiVGhvbWFzIiwiYXV0aG9yaXRpZXMiOiJSRUFEX0FSVElDTEV8UkVBRF9PUkRFUnxXUklURV9PUkRFUnxDUkVBVEVfT1JERVJ8REVMRVRFX09SREVSIiwiZXhwIjoxNjE1NzIyNDg2fQ.r6Rrq_-KPlon6-UT_r9mKFqNq525UAbYPa2aMZ8W9kIhoF-myOVFq5YMU_esrsIbyOJfFS9CalQGobr-GhglQA

###

POST http://localhost:8080/login?username=John&password=Passw0rt

###

POST http://localhost:8080/articles
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdWRpZW5jZSI6InR3cnNwcnNlYyIsInN1YmplY3QiOiJUaG9tYXMiLCJpc3N1ZXIiOiJUaG9tYXMiLCJhdXRob3JpdGllcyI6IlBST0NFU1NfSEVMTE98REVMRVRFX0FSVElDTEV8Q1JFQVRFX09SREVSfFdSSVRFX0FSVElDTEV8UkVBRF9PUkRFUnxERUxFVEVfT1JERVJ8V1JJVEVfT1JERVJ8UkVBRF9BUlRJQ0xFfENSRUFURV9BUlRJQ0xFIiwiZXhwIjoxNjE1NzQxMzg2fQ.5ftYvnPF2Mzf6vfFGr67TxsDzWD_u4cU1_huo4WzZa8v9HM2_OHQ-pXeZC67AHVnN7_cVSe1c36ri2tqqiJcQQ

###

POST http://localhost:8080/login?username=Thomas&password=Passw0rt

###

GET http://localhost:8080/articles/1234
Authorization: Basic Thomas Passw0rt

<> 2021-03-07T175308.200.txt

###

GET http://localhost:8080/articles/1234
Authorization: Basic John Passw0rt

<> 2021-03-07T175258.403.json

###

GET http://localhost:8080/hello
Authorization: Basic John Passw0rt

<> 2021-03-07T175245.200.txt

###

GET http://localhost:8080/articles/1234
Authorization: Basic Thomas Passw0rt

<> 2021-03-07T175202.200.txt

###

GET http://localhost:8080/articles/1234
Authorization: Basic John Passw0rt

<> 2021-03-07T175157.403.json

###

GET http://localhost:8080/orders/1234
Authorization: Basic John Passw0rt

<> 2021-03-07T175151.200.txt

###

GET http://localhost:8080/orders/1234
Authorization: Basic Thomas Passw0rt

<> 2021-03-07T175123.200.txt

###

GET http://localhost:8080/orders/1234
Authorization: Basic Thomas Passw0rt

<> 2021-03-07T175106.404.json

###

GET http://localhost:8080/orders/1234
Authorization: Basic Thomas Passw0rt

<> 2021-03-07T175017.404.json

###

GET http://localhost:8080/articles/1234
Authorization: Basic John Passw0rt

###

GET http://localhost:8080/articles/1234
Authorization: Basic Thomas Passw0rt

<> 2021-03-07T174931.200.txt

###

GET http://localhost:8080/hello
Authorization: Basic Thomas Passw0rt

<> 2021-03-07T174845.200.txt

###

GET http://localhost:8080/articles/1234
Authorization: Basic Thomas Passw0rt

<> 2021-03-07T174750.200.txt

###

GET http://localhost:8080/articles/1234
Authorization: Basic Thomas Passw0rt

<> 2021-03-07T172818.200.txt

###

GET http://localhost:8080/articles/1234
Authorization: Basic Thomas Passw0rt

<> 2021-03-07T172537.500.json

###

GET http://localhost:8080/articles/1234

<> 2021-03-07T172433.401.json

###

GET http://articles/1234

###

