GET http://localhost:8080/hello

###
GET http://localhost:8080/hello
Authorization: Basic John Passw0rt

###
GET http://localhost:8080/hello
Authorization: Basic Thomas Passw0rt

###
GET http://localhost:8080/articles/123

###
GET http://localhost:8080/articles/123
Authorization: Basic Thomas Passw0rt

###
GET http://localhost:8080/articles/123
Authorization: Basic John Passw0rt

###
GET http://localhost:8080/orders/123

###
GET http://localhost:8080/orders/123
Authorization: Basic Thomas Passw0rt

###
GET http://localhost:8080/orders/123
Authorization: Basic John Passw0rt

###
GET http://localhost:8080/articles/123
Authorization: Basic John Passw0rt

###
POST http://localhost:8080/articles/123
Authorization: Basic John Passw0rt

###
POST http://localhost:8080/login?username=Thomas&password=Passw0rt

###
GET http://localhost:8080/hello
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdWRpZW5jZSI6InR3cnNwcnNlYyIsInN1YmplY3QiOiJUaG9tYXMiLCJpc3N1ZXIiOiJUaG9tYXMiLCJhdXRob3JpdGllcyI6IldSSVRFX0FSVElDTEV8V1JJVEVfT1JERVJ8REVMRVRFX0FSVElDTEV8REVMRVRFX09SREVSfENSRUFURV9BUlRJQ0xFfFJFQURfT1JERVJ8Q1JFQVRFX09SREVSfFBST0NFU1NfSEVMTE98UkVBRF9BUlRJQ0xFIiwiZXhwIjoxNjE1NzE5ODE4fQ.nVjPlhCIg2cIWUU0Z8A-nhz9VeDoZNYL0mecAk3er065fklNI1pOt85f7Az8JfQgNlAjgLBG7kutJtwrnBvYaw

###
POST http://localhost:8080/articles



###
POST http://localhost:8080/articles
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdWRpZW5jZSI6InR3cnNwcnNlYyIsInN1YmplY3QiOiJUaG9tYXMiLCJpc3N1ZXIiOiJUaG9tYXMiLCJhdXRob3JpdGllcyI6IldSSVRFX0FSVElDTEV8V1JJVEVfT1JERVJ8REVMRVRFX0FSVElDTEV8REVMRVRFX09SREVSfENSRUFURV9BUlRJQ0xFfFJFQURfT1JERVJ8Q1JFQVRFX09SREVSfFBST0NFU1NfSEVMTE98UkVBRF9BUlRJQ0xFIiwiZXhwIjoxNjE1NzE5ODE4fQ.nVjPlhCIg2cIWUU0Z8A-nhz9VeDoZNYL0mecAk3er065fklNI1pOt85f7Az8JfQgNlAjgLBG7kutJtwrnBvYaw

###
POST http://localhost:8080/login?username=John&password=Passw0rt

###
POST http://localhost:8080/articles
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdWRpZW5jZSI6InR3cnNwcnNlYyIsInN1YmplY3QiOiJKb2huIiwiaXNzdWVyIjoiVGhvbWFzIiwiYXV0aG9yaXRpZXMiOiJXUklURV9PUkRFUnxERUxFVEVfT1JERVJ8UkVBRF9PUkRFUnxDUkVBVEVfT1JERVJ8UkVBRF9BUlRJQ0xFIiwiZXhwIjoxNjE1NzE5OTgxfQ.ZEoVfwbYrUJugmo0PKLpPmRKzxQ8xpJHpTh1H-1ZhIA8n7eqXatZE1TLeqsZNfrsCQJPWfY-Ts8JMAj342KfEQ
